image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
    - name: Setup, Install & Build
      before: curl -L https://foundry.paradigm.xyz | bash && source ~/.bashrc && foundryup