# SPDX-License-Identifier: NOASSERTION
#
# SPDX-FileType: SOURCE
#
# SPDX-FileCopyrightText: 2024 Johannes Krauser III <krauser@co.xyz>, Zodomo <zodomo@proton.me>
#
# SPDX-FileContributor: Zodomo <zodomo@proton.me>

bracketSpacing: true
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 4
trailingComma: "all"
useTabs: false
