# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# SPDX-License-Identifier: NOASSERTION
#
# SPDX-FileType: SOURCE
#
# SPDX-FileCopyrightText: 2024 Johannes Krauser III <krauser@co.xyz>
# 
# SPDX-FileContributor: Johannes Krauser III <krauser@co.xyz>

[profile.default]
auto_detect_solc = false
evm_version = "paris"
bytecode_hash = "none"
fuzz = { runs = 10 }
gas_reports = ["*"]
optimizer = true
out = "out"
script = "src/script"
solc = "0.8.23"
src = "src/contracts"
test = "src/test"
libs = ["node_modules", "lib"]

[profile.ci]
fuzz = { runs = 100 }
verbosity = 4


[fmt]
bracket_spacing = false
func_attrs_with_params_multiline = false
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = 'preserve'
sort_imports = true
tab_width = 4
variable_override_spacing = true
wrap_comments = true

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
